"use client";
import * as React from "react";
import ThemeRegistry from "./ThemeRegistry";
import Header from "@/components/Header";
import { Box } from "@mui/joy";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  session: Session | null;
  children: React.ReactNode;
}

export default function RootLayout({ children,  session }: Props) {

  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <SessionProvider session={session}>
            <Header />
            <Box
              component="main"
              className="MainContent"
              sx={{
                px: {
                  xs: 2,
                  md: 6,
                },
                pt: {
                  xs: "calc(20px + var(--Header-height))",
                  sm: "calc(20px + var(--Header-height))",
                  md: "calc(20px + var(--Header-height))",
                },
                pb: {
                  xs: 2,
                  sm: 2,
                  md: 3,
                },
                flex: 1,
                gap: 1,
              }}
            >
              {children}
            </Box>
          </SessionProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
