import * as React from "react";
import ThemeRegistry from "./ThemeRegistry";
import Header from "@/components/Header";
import { Box } from "@mui/joy";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Header />
          <Box
            component="main"
            className="MainContent"
            sx={{
              px: {
                xs: 2,
                md: 6,
              },
              pt: {
                xs: "calc(20px + var(--Header-height))",
                sm: "calc(20px + var(--Header-height))",
                md: "calc(20px + var(--Header-height))",
              },
              pb: {
                xs: 2,
                sm: 2,
                md: 3,
              },
              flex: 1,
              gap: 1,
            }}
          >
            {children}
          </Box>
        </ThemeRegistry>
      </body>
    </html>
  );
}
