"use client";
import * as React from "react";
import ThemeRegistry from "./ThemeRegistry";
import Header from "@/components/Header";
import { Box } from "@mui/joy";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

interface Props {
  session: Session | null;
  children: React.ReactNode;
}

export default function RootLayout({ children, session }: Props) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <SessionProvider session={session}>
            <Header />
            <Box
              display="flex"
              justifyContent="center"
              alignItems="center"
              sx={{ mt: 10 }}
            >
              {children}
            </Box>
          </SessionProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
